### ISSUE TITLE
https://xojoc.pw certificate expired

### ISSUE THREAD

**Issue by gugu** [xojoc/useragent#18]
And as it is used expired it is not possible download a module as it is written in the docs

**Comment by dbemiller** [comment]
Same issue here... we're pulling this project in through `glide.yaml`:

```
- package: xojoc.pw/useragent
```

It's been working fine until today... where `glide install` fails with the following:
```
WARN]	Unable to checkout xojoc.pw/useragent
[ERROR]	Update failed for xojoc.pw/useragent: Cannot detect VCS
```

Probably also due to this issue.

**Comment by pauldub** [comment]
You can use the github.com import as a fix for this issue.

**Comment by dbemiller** [comment]
We were using that originally... but actually changed to `xojoc.pw/useragent` because it was breaking `go get` on our project: https://github.com/prebid/prebid-server/pull/64

**Comment by gugu** [comment]
@dbemiller @pauldub you can use this repo: https://github.com/RenaultAI/useragent, it works

**Comment by dbemiller** [comment]
Thanks!

...since our project's dependency was very thin, though, and the owner didn't respond, we already switched over to github.com/mssola/user_agent.

**Comment by moonmeister** [comment]
@dbemiller mssola/user_agent works but is not maintained terribly well and the code is a spaghetti nightmare. If it works for you great but I thought I'd share my experience/opinion. Here's another option if you're interested. https://github.com/avct/uasurfer

**Comment by majimboo** [comment]
Hoping this to be fixed soon...

`package xojoc.pw/useragent: unrecognized import path "xojoc.pw/useragent" (https fetch: Get https://xojoc.pw/useragent?go-get=1: x509: certificate has expired or is not yet valid)`

**Comment by dvrkps** [comment]
Should be working now.

**Comment by xojoc** [comment]
Fixed, sorry for the late answer :)
