### ISSUE TITLE
Misidentify microsoft edge with Chrome

### ISSUE THREAD

**Issue by DxTa** [xojoc/useragent#4]
I've got this error when using Microsoft Edge or using this below user agent string:

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by brendanwalters** [comment]
This should be closed by PR #12

**Comment by xojoc** [comment]
@brendanwalters thanks :+1:
